sudo: required
language: python
python:
- '2.7'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libssl-dev
    - protobuf-compiler
    - libprotobuf-dev
services:
- docker
before_install:
- pip install protobuf pyzmq
- git clone https://github.com/AO-StreetArt/DvsInterface.git
- cd DvsInterface && sudo make install
- cd $TRAVIS_BUILD_DIR
- git clone https://github.com/AO-StreetArt/0-Meter.git
- git clone https://github.com/AO-StreetArt/PythonCsvHelper.git
- docker network create dvs
install:
- cd $TRAVIS_BUILD_DIR
- docker pull consul
- docker run -d --name=registry --network=dvs consul
- docker pull mongo
- docker run -d --network=dvs --name=document-db mongo
- docker pull spotify/kafka
- docker run -i -t -d -p 2181:2181 -p 9092:9092 --env ADVERTISED_PORT=9092 --env ADVERTISED_HOST=queue --name=queue --network=dvs spotify/kafka
- docker exec -t registry curl -X PUT -d 'mongodb://document-db:27017/' http://localhost:8500/v1/kv/clyman/Mongo_ConnectionString
- docker exec -t registry curl -X PUT -d 'queue:9092' http://localhost:8500/v1/kv/clyman/KafkaBrokerAddress
- docker exec -t registry curl -X PUT -d 'mydb' http://localhost:8500/v1/kv/clyman/Mongo_DbName
- docker exec -t registry curl -X PUT -d 'test' http://localhost:8500/v1/kv/clyman/Mongo_DbCollection
- docker exec -t registry curl -X PUT -d 'True' http://localhost:8500/v1/kv/clyman/StampTransactionId
- docker exec -t registry curl -X PUT -d 'True' http://localhost:8500/v1/kv/clyman/ObjectLockingActive
- docker exec -t registry curl -X PUT -d 'JSON' http://localhost:8500/v1/kv/clyman/DataFormatType
- cd $TRAVIS_BUILD_DIR/scripts/linux && ./run_test_consumer.sh
- cd $TRAVIS_BUILD_DIR/scripts/linux && ./build_docker_instance.sh $TRAVIS_BRANCH
  $TRAVIS_BUILD_DIR
- cd $TRAVIS_BUILD_DIR/scripts/linux && ./run_docker_instance.sh $TRAVIS_BRANCH registry:8500
  localhost 5556
before_script:
- sleep 5
- docker ps -a
- docker logs clyman
- docker logs document-db
- docker logs registry
script:
- cd $TRAVIS_BUILD_DIR && python ci/py/basicClymanFlow.py
- cat basicClymanFlow.log
- cd $TRAVIS_BUILD_DIR && python 0-Meter/0-meter.py ci/obj_crt.xml
- tail $TRAVIS_BUILD_DIR/obj_crt.log
- docker logs --tail 75 clyman
- cd $TRAVIS_BUILD_DIR && python PythonCsvHelper/CsvHelper.py obj_crt_out.csv ci/csv/obj_get.csv
  0 3
- cd $TRAVIS_BUILD_DIR && python PythonCsvHelper/CsvHelper.py obj_crt_out.csv ci/csv/obj_upd.csv
  0 3
- cd $TRAVIS_BUILD_DIR && python PythonCsvHelper/CsvHelper.py obj_crt_out.csv ci/csv/obj_overwrite.csv
  0 3
- cd $TRAVIS_BUILD_DIR && python PythonCsvHelper/CsvHelper.py obj_crt_out.csv ci/csv/obj_delete.csv
  0 3
- cd $TRAVIS_BUILD_DIR && python PythonCsvHelper/CsvHelper.py obj_crt_out.csv ci/csv/obj_lock.csv
  0 3
- cd $TRAVIS_BUILD_DIR && python PythonCsvHelper/CsvHelper.py obj_crt_out.csv ci/csv/obj_lock_bad.csv
  0 3
- cd $TRAVIS_BUILD_DIR && python PythonCsvHelper/CsvHelper.py obj_crt_out.csv ci/csv/obj_unlock.csv
  0 3
- cd $TRAVIS_BUILD_DIR && python 0-Meter/0-meter.py ci/obj_get.xml
- tail $TRAVIS_BUILD_DIR/obj_get.log
- docker logs --tail 75 clyman
- cd $TRAVIS_BUILD_DIR && python 0-Meter/0-meter.py ci/obj_upd.xml
- tail $TRAVIS_BUILD_DIR/obj_upd.log
- docker logs --tail 75 clyman
- cd $TRAVIS_BUILD_DIR && python 0-Meter/0-meter.py ci/obj_overwrite.xml
- tail $TRAVIS_BUILD_DIR/obj_overwrite.log
- docker logs --tail 75 clyman
- cd $TRAVIS_BUILD_DIR && python 0-Meter/0-meter.py ci/obj_name_query.xml
- tail $TRAVIS_BUILD_DIR/obj_name_query.log
- docker logs --tail 75 clyman
- cd $TRAVIS_BUILD_DIR && python 0-Meter/0-meter.py ci/obj_lock.xml
- tail $TRAVIS_BUILD_DIR/obj_lock.log
- docker logs --tail 75 clyman
- cd $TRAVIS_BUILD_DIR && python 0-Meter/0-meter.py ci/obj_lock_bad.xml
- tail $TRAVIS_BUILD_DIR/obj_lock.log
- docker logs --tail 50 clyman
- cd $TRAVIS_BUILD_DIR && python 0-Meter/0-meter.py ci/obj_unlock.xml
- tail $TRAVIS_BUILD_DIR/obj_unlock.log
- docker logs --tail 50 clyman
- cd $TRAVIS_BUILD_DIR && python 0-Meter/0-meter.py ci/obj_lock_second.xml
- tail $TRAVIS_BUILD_DIR/obj_lock.log
- docker logs --tail 50 clyman
- cd $TRAVIS_BUILD_DIR && python 0-Meter/0-meter.py ci/obj_del.xml
- tail $TRAVIS_BUILD_DIR/obj_del.log
- docker logs --tail 75 clyman
- cd $TRAVIS_BUILD_DIR && python 0-Meter/0-meter.py ci/obj_get_bad.xml
- tail $TRAVIS_BUILD_DIR/obj_get.log
- docker logs --tail 60 clyman
- cd $TRAVIS_BUILD_DIR && python 0-Meter/0-meter.py ci/obj_upd_bad.xml
- tail $TRAVIS_BUILD_DIR/obj_upd.log
- docker logs --tail 60 clyman
- cd $TRAVIS_BUILD_DIR && python 0-Meter/0-meter.py ci/obj_name_query_bad.xml
- tail $TRAVIS_BUILD_DIR/obj_name_query.log
- docker logs --tail 60 clyman
- cd $TRAVIS_BUILD_DIR && python 0-Meter/0-meter.py ci/obj_type_query_bad.xml
- tail $TRAVIS_BUILD_DIR/obj_type_query.log
- docker logs --tail 60 clyman
- cd $TRAVIS_BUILD_DIR && python 0-Meter/0-meter.py ci/obj_del_bad.xml
- tail $TRAVIS_BUILD_DIR/obj_del.log
- docker logs --tail 60 clyman
- cd $TRAVIS_BUILD_DIR && python 0-Meter/0-meter.py ci/obj_crt_bad.xml
- tail $TRAVIS_BUILD_DIR/obj_crt.log
- docker logs --tail 60 clyman
- docker logs --tail 150 test_consumer
after_success:
- cd $TRAVIS_BUILD_DIR/scripts/linux && ./push_docker_instance.sh $DOCKER_MAIL $DOCKER_UN
  $DOCKER_PW $TRAVIS_BRANCH $TRAVIS_BUILD_DIR
notifications:
  slack:
    secure: xcrx4Sh5DLlDyI10jBTNYdQZzIROwx6MeQQqWIRTbEetqPsZhyr9bQK+P9rqhePsWyY/tLMAC4DWMLGZTG6U5z1OSjJTTJFNyljrZdHxUl0zK9tnq5CHXptIoYcsd918IF6X0rnsxjt/bTSMRv95nafhi3xwOn2j6PJVJHUaqnIXiJFKF+uhzZ+jZ+o2uimsCZU+YTCn+170Q7yqeyw+zMhml62Ub2AOemE3LCwQsQypPRs6hUuXouLPbOG2P0L9yDYDdzFfO56bO6fKlr4YsksNO6gY8XlfERsUjQZtWj737GP5AAcKMmjssoVNw9gmULQvw0gOrZBN8t9dWNvpOcchepJQ3Peb9CY9pF4Zqsousvpym/F2kVPnnXXoFzPP5lqOcDMUyH1ocDmDp+Gwmnbl2PN4ZvI9NJ+9W5qseoUnnZvY7yLq6zMhDhuDqGarSHeouEHtHSUrYBbtG/0GuEBx/3EHe7944SwJiiCrxgFh1azV4kYq3lFw8ZZwy7QImYICpjllqGOwUyC/vqNNbjaGlmYQvlfUxteaxYnCMUzWBt32SnmWR6+Io5qUPISgOinqRxcTe+LYWB/B7Ll8wxsHoVynd2MFkDXjbnZcviCu8WQBBXH5EX4mbcLwN2An0g+Ts5+znYbbzWMtdwMOiMXSSIpdWxfLwQPLKCbloZI=
