# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: precise
language: cpp

sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
services:
  - redis-server
before_install:
  - sudo apt-get install libssl-dev
  - mkdir ../clyman_deps
  - sudo cp scripts/linux/deb/build_deps.sh ../clyman_deps
  - cd ../clyman_deps && sudo ./build_deps.sh
  - cat build_deps.log
  - cd $TRAVIS_BUILD_DIR
install:
  - cd scripts && sudo ./install_couchbase.sh
  - cd $TRAVIS_BUILD_DIR
  - wget https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_linux_amd64.zip
  - unzip consul_0.6.4_linux_amd64.zip
  - ./consul agent -dev &
script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - gcc --version
  - make rhel
  - make rhel-test
  - make rhel-benchmarks
  - ./obj3_test &
  - ./configuration_test
