# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: trusty
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    # Install GCC
    - gcc-5
    - g++-5
    # Install Python
    - python
    - python-dev
    - python-pip
    # Install LibSSL
    - libssl-dev
    # Install Protocol Buffer Compiler
    - protobuf-compiler
    - libprotobuf-dev
services:
  # Start up Docker
  - docker
before_install:
  - cd $TRAVIS_BUILD_DIR/scripts/linux && ./ci_preinstall $TRAVIS_BUILD_DIR
install:
  - cd $TRAVIS_BUILD_DIR/scripts/linux && ./ci_install $TRAVIS_BUILD_DIR $TRAVIS_BRANCH
script:
  - cd $TRAVIS_BUILD_DIR/scripts/linux && ./run_success_tests $TRAVIS_BUILD_DIR
  - cd $TRAVIS_BUILD_DIR/scripts/linux && ./run_failure_tests $TRAVIS_BUILD_DIR
after_success:
  - script: cd $TRAVIS_BUILD_DIR/scripts/linux && ./push_docker_instance.sh $DOCKER_MAIL $DOCKER_UN $DOCKER_PW $TRAVIS_BRANCH $TRAVIS_BUILD_DIR
