version: '3.0'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
  clyman:
    image: aostreetart/clyman:v2
    container_name: clyman
    ports:
      - "8768:8768"
      - "8762:8762/udp"
    command: clyman.prod.mongo=mongodb://localhost:27017 clyman.prod.http.host=clyman clyman.prod.http.port=8768 clyman.prod.udp.port=8762
