# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Obj3.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Obj3.proto',
  package='protoObj3',
  serialized_pb='\n\nObj3.proto\x12\tprotoObj3\"\xb6\x04\n\x04Obj3\x12\x14\n\x0cmessage_type\x18\x01 \x02(\x05\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x0f\n\x07subtype\x18\x05 \x01(\t\x12\r\n\x05owner\x18\x06 \x01(\t\x12\x16\n\x0elock_device_id\x18\x07 \x01(\t\x12)\n\x08location\x18\x08 \x01(\x0b\x32\x17.protoObj3.Obj3.Vertex3\x12/\n\x0erotation_euler\x18\t \x01(\x0b\x32\x17.protoObj3.Obj3.Vertex3\x12\x34\n\x13rotation_quaternion\x18\n \x01(\x0b\x32\x17.protoObj3.Obj3.Vertex4\x12&\n\x05scale\x18\x0b \x01(\x0b\x32\x17.protoObj3.Obj3.Vertex3\x12*\n\ttransform\x18\x0c \x01(\x0b\x32\x17.protoObj3.Obj3.Matrix4\x12-\n\x0c\x62ounding_box\x18\r \x01(\x0b\x32\x17.protoObj3.Obj3.Matrix4\x12\x0e\n\x06scenes\x18\x0e \x03(\t\x1a*\n\x07Vertex3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x1a\x35\n\x07Vertex4\x12\t\n\x01w\x18\x01 \x01(\x01\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\x1a/\n\x07Matrix4\x12$\n\x03\x63ol\x18\x01 \x03(\x0b\x32\x17.protoObj3.Obj3.Vertex4')




_OBJ3_VERTEX3 = _descriptor.Descriptor(
  name='Vertex3',
  full_name='protoObj3.Obj3.Vertex3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='protoObj3.Obj3.Vertex3.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='protoObj3.Obj3.Vertex3.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='protoObj3.Obj3.Vertex3.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=446,
  serialized_end=488,
)

_OBJ3_VERTEX4 = _descriptor.Descriptor(
  name='Vertex4',
  full_name='protoObj3.Obj3.Vertex4',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='w', full_name='protoObj3.Obj3.Vertex4.w', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='protoObj3.Obj3.Vertex4.x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='protoObj3.Obj3.Vertex4.y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='protoObj3.Obj3.Vertex4.z', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=490,
  serialized_end=543,
)

_OBJ3_MATRIX4 = _descriptor.Descriptor(
  name='Matrix4',
  full_name='protoObj3.Obj3.Matrix4',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='col', full_name='protoObj3.Obj3.Matrix4.col', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=545,
  serialized_end=592,
)

_OBJ3 = _descriptor.Descriptor(
  name='Obj3',
  full_name='protoObj3.Obj3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_type', full_name='protoObj3.Obj3.message_type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='protoObj3.Obj3.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='protoObj3.Obj3.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='protoObj3.Obj3.type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subtype', full_name='protoObj3.Obj3.subtype', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner', full_name='protoObj3.Obj3.owner', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lock_device_id', full_name='protoObj3.Obj3.lock_device_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='protoObj3.Obj3.location', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rotation_euler', full_name='protoObj3.Obj3.rotation_euler', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rotation_quaternion', full_name='protoObj3.Obj3.rotation_quaternion', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scale', full_name='protoObj3.Obj3.scale', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transform', full_name='protoObj3.Obj3.transform', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bounding_box', full_name='protoObj3.Obj3.bounding_box', index=12,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scenes', full_name='protoObj3.Obj3.scenes', index=13,
      number=14, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_OBJ3_VERTEX3, _OBJ3_VERTEX4, _OBJ3_MATRIX4, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=26,
  serialized_end=592,
)

_OBJ3_VERTEX3.containing_type = _OBJ3;
_OBJ3_VERTEX4.containing_type = _OBJ3;
_OBJ3_MATRIX4.fields_by_name['col'].message_type = _OBJ3_VERTEX4
_OBJ3_MATRIX4.containing_type = _OBJ3;
_OBJ3.fields_by_name['location'].message_type = _OBJ3_VERTEX3
_OBJ3.fields_by_name['rotation_euler'].message_type = _OBJ3_VERTEX3
_OBJ3.fields_by_name['rotation_quaternion'].message_type = _OBJ3_VERTEX4
_OBJ3.fields_by_name['scale'].message_type = _OBJ3_VERTEX3
_OBJ3.fields_by_name['transform'].message_type = _OBJ3_MATRIX4
_OBJ3.fields_by_name['bounding_box'].message_type = _OBJ3_MATRIX4
DESCRIPTOR.message_types_by_name['Obj3'] = _OBJ3

class Obj3(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Vertex3(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _OBJ3_VERTEX3

    # @@protoc_insertion_point(class_scope:protoObj3.Obj3.Vertex3)

  class Vertex4(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _OBJ3_VERTEX4

    # @@protoc_insertion_point(class_scope:protoObj3.Obj3.Vertex4)

  class Matrix4(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _OBJ3_MATRIX4

    # @@protoc_insertion_point(class_scope:protoObj3.Obj3.Matrix4)
  DESCRIPTOR = _OBJ3

  # @@protoc_insertion_point(class_scope:protoObj3.Obj3)


# @@protoc_insertion_point(module_scope)
